### ISSUE TITLE
Project TODO List - Remaining Issues

### ISSUE THREAD

**Issue by whyjay17** [whyjay17/cs527_project#1]
- [x] Finish visualization

- [x] Add visualization to PDF

- [x] Fix directory path issue

- [x] Package manager

- [x] Exclude standard library or package in Shotgun Surgery

- [x] Polish PDF
